#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from builtin_interfaces.msg import Duration

from std_msgs.msg import String, Float64
from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint
from std_srvs.srv import Empty

class MoveArm(Node):

    def __init__(self):
        super().__init__('arm_node')
        self.canadarm2_publisher_ = self.create_publisher(JointTrajectory, '/canadarm2_joint_trajectory_controller/joint_trajectory', 10)
        self.mbs_publisher_ = self.create_publisher(JointTrajectory, '/mobile_base_system_joint_trajectory_controller/joint_trajectory', 10)
        
        self.canadarm2_pose_0_srv = self.create_service(Empty, 'canadarm2_pose_0', self.canadarm2_pose_0_callback)
        self.canadarm2_pose_1_srv = self.create_service(Empty, 'canadarm2_pose_1', self.canadarm2_pose_1_callback)

        self.mbs_pose_0_srv = self.create_service(Empty, 'mbs_pose_0', self.mbs_pose_0_callback)
        self.mbs_pose_1_srv = self.create_service(Empty, 'mbs_pose_1', self.mbs_pose_1_callback)
        self.mbs_pose_2_srv = self.create_service(Empty, 'mbs_pose_2', self.mbs_pose_1_callback)

        self.canadarm2_joints = ["joint_canadarm2_1", "joint_canadarm2_2", "joint_canadarm2_3", "joint_canadarm2_4", "joint_canadarm2_5", "joint_canadarm2_6", "joint_canadarm2_7"]

        self.mbs_joints = ["joint_mbs"]

    def canadarm2_pose_0_callback(self, request, response):
        traj = JointTrajectory()
        traj.joint_names = self.canadarm2_joints
        
        point1 = JointTrajectoryPoint()
        point1.positions = [0.0, 0.628, -0.187, 0.0, 0.0, 0.0, 0.0]
        point1.time_from_start = Duration(sec=30)

        traj.points.append(point1)
        self.canadarm2_publisher_.publish(traj)

        return response

    def canadarm2_pose_1_callback(self, request, response):
        traj = JointTrajectory()
        traj.joint_names = self.canadarm2_joints
        
        point1 = JointTrajectoryPoint()
        point1.positions = [0.51, 1.48, -0.677, 0.534, -0.062, -0.645, -0.755]
        point1.time_from_start = Duration(sec=30)

        traj.points.append(point1)
        self.canadarm2_publisher_.publish(traj)

        return response

    def mbs_pose_0_callback(self, request, response):
        traj = JointTrajectory()
        traj.joint_names = self.mbs_joints
        
        point1 = JointTrajectoryPoint()
        point1.positions = [0.0]
        point1.time_from_start = Duration(sec=30)

        traj.points.append(point1)
        self.mbs_publisher_.publish(traj)

        return response

    def mbs_pose_1_callback(self, request, response):
        traj = JointTrajectory()
        traj.joint_names = self.mbs_joints
        
        point1 = JointTrajectoryPoint()
        point1.positions = [8.0]
        point1.time_from_start = Duration(sec=30)

        traj.points.append(point1)
        self.mbs_publisher_.publish(traj)

        return response

    def mbs_pose_2_callback(self, request, response):
        traj = JointTrajectory()
        traj.joint_names = self.mbs_joints
        
        point1 = JointTrajectoryPoint()
        point1.positions = [-4.0]
        point1.time_from_start = Duration(sec=30)

        traj.points.append(point1)
        self.mbs_publisher_.publish(traj)

        return response




def main(args=None):
    rclpy.init(args=args)

    arm_node = MoveArm()

    rclpy.spin(arm_node)
    # Destroy the node explicitly
    # (optional - otherwise it will be done automatically
    # when the garbage collector destroys the node object)
    arm_node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
